[package]
name = "cipher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.0"
tempfile = "3.3.0"
rand = "0.9.0"
serde_json = "1.0.138"
log = "0.4.25"
env_logger = "0.11.6"

[profile.release]
strip = true
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
